name: "developer  workflow"

on:
    push:
        branches:
            - developer/v1.0
    workflow_dispatch:

permissions:
    contents: read # Required for actions/checkout
    security-events: write # Required for github/codeql-action/upload-sarif@v3

jobs:
    dev-ci:
        runs-on: self-hosted
        steps:
            # --- Order Service Build and Scan ---
            - name: Build and export order service to Docker
              uses: docker/build-push-action@v6
              with:
                  context: ./src/order-service
                  load: true # Exports the image to the local Docker daemon for Trivy scanning
                  tags: shaikkhajaibrahim/devorder-service:latest
                  push: true

            # --- Product Service Build and Scan ---
            - name: Build and export product service to Docker
              uses: docker/build-push-action@v6
              with:
                  context: ./src/product-service
                  load: true
                  tags: shaikkhajaibrahim/devproduct-service
                  push: true
